name: healthapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  lottie: ^1.3.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  dart_code_metrics: ^4.15.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/
    - assets/jsons/images/